name: Profile Summary Cards
on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # counts private too
        with:
          USERNAME: <USERNAME>
          THEME: github_dark          # try: 2077, radical, dracula, monokai
          OUTPUT_DIR: profile-summary-card-output
